### ISSUE TITLE
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

### ISSUE THREAD

**Issue by d10-cat** [hoprnet/hopr-analytics#8]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 185.0 HOPR (109.39 USD @ $0.59/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-analytics/7/100025611).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $1,970,640.91 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

_Originally posted by @gitcoinbot in https://github.com/hoprnet/hopr-analytics/issues/7#issuecomment-828350021_

**Comment by d10-cat** [comment]
Normally I wouldn’t do this bad for Bussiness on my side 

honestly you guys need to do and epic airdrop 
That would increase your following by x3.5 if you go all out give away 1500000 coins they’re going to be traded and spent then fork your burn pile auto regain revenue I expect gratuity I just saved you months

**Comment by QYuQianchen** [comment]
Close due to irrelevance to the purpose of the repo.
